alias c="clear"
alias v="nvim"
alias profile="nvim ~/.dotfiles/.profile_rc"
alias zshrc="nvim ~/.zshrc"
alias ll="ls -la"
alias ls="eza --color=always --long --git --icons=always --no-time --no-user"
alias cd="z"
alias ff="cd ~/.mozilla/firefox/8wkd340m.default-nightly/chrome"
alias kitty="~/.local/kitty.app/bin/kitty"
