# Application Directory
# cask_args appdir: '/Applications:'

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/cask-fonts'

brew 'bat'
brew 'git'
brew 'wget'
brew 'openssl'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'node'
brew 'yarn'
brew 'neovim'
brew 'rbenv'

# Apps
cask 'spotify'
cask 'firefox'
cask 'docker'
cask 'zoom'
cask 'vlc'
cask 'visual-studio-code'
cask 'alfred'
cask 'brave-browser'

# Fonts
cask 'font-hack-nerd-font'
cask 'font-fira-code'
cask 'font-meslo-lg-nerd-font'

